# Generated by Django 3.2.12 on 2024-08-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_title',
            field=models.TextField(default='Note title', max_length=50),
        ),
    ]
