# Generated by Django 3.2.12 on 2024-08-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notesContent',
            field=models.TextField(max_length=1024),
        ),
    ]
