# Generated by Django 3.2.12 on 2024-08-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_note_notescontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_title',
            field=models.CharField(default='Note title', max_length=50),
        ),
    ]
