# Generated by Django 3.2.12 on 2024-08-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_note_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_title',
            field=models.CharField(max_length=50),
        ),
    ]
