# Generated by Django 3.2.12 on 2024-08-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_note_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
